\LoadClass{article}
\usepackage[utf8]{inputenc}
\usepackage[noend]{algcompatible}
\usepackage{algorithm}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage[english]{babel}
\usepackage[justification=centering]{caption}
\usepackage{changepage}
\usepackage{color}
\usepackage{empheq}
\usepackage[shortlabels]{enumitem}
\usepackage{fancyhdr}
\usepackage{float}
\usepackage{framed}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{mathrsfs}
\usepackage{mathtools}
\usepackage{nameref}
\usepackage{setspace}
\usepackage{subcaption}
\usepackage{tcolorbox}
\usepackage{tikz}
\usepackage[normalem]{ulem}

% Page settings
\allowdisplaybreaks
\frenchspacing
\setlength{\headheight}{14pt}
\pagenumbering{arabic}
\pagestyle{fancy}
\captionsetup[subfigure]{justification=justified}

\DeclareMathOperator\E{E}
